Repository knadh/listmonk, pull requests merged in 2024-08, with the labels that each got.

#1965 fix #1950:Export of unsubscribed users exports all users
  cmd/subscribers.go
  frontend/src/views/Subscribers.vue
  internal/core/subscribers.go
  queries.sql
Labels: bug

#1973 add error message for filename with non-ascii chars
  cmd/media.go
  cmd/utils.go
  docs/docs/content/apis/apis.md
  i18n/en.json
Labels: enhancement

#2007 Fix #1979: syntax error in GetBounce method
  internal/core/bounces.go
Labels: minor-bug
